version: '2'
services:
  coiniumserv:
    container_name: coinserv
    build: .
    image: coinium_serv
    ports:
      - "5432:5432"
#    entrypoint: mono ./CoiniumServ-master/bin/Release/CoiniumServ.exe

  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
